version: 2.1

jobs:
  build-and-test:
    
    docker:
      - image: circleci/python:3.6.9-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "requirements.txt" }}
            - v3-dependencies

      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v3-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Execute thepulper webpage
          command: |
            java -jar thepulper-1-2-5-jar-with-dependencies.jar
          background: true

      - run:
          name: Run test suite
          command: |
            source ./venv/bin/activate
            pytest tests/ -v

workflows:
  main:
    jobs:
      - build-and-test
